# Install:
#  /etc/entervices/privacyConfig.json
IMAGE_CLASSES += "entservicesprivacyconfig"

#  /etc/migration/entos_apps_migration.json
IMAGE_CLASSES += "appsmigrationconfig"

# /etc/sky/aisettings.overrides/migration-override.json
IMAGE_CLASSES += "aimigrationoverrideconfig"

# /etc/ripple/rdke/northamerica/ripple.config.json
IMAGE_CLASSES += "ripplemigrationoverrideconfig"

# /etc/migration/boot_FSR.platform
IMAGE_CLASSES += "bootfsrconfig"
