# Install:
#  /etc/migration/entos_apps_migration.json
IMAGE_CLASSES += "appsmigrationconfig"

# /etc/sky/aisettings.overrides/migration-override.json
IMAGE_CLASSES += "aimigrationoverrideconfig"

# /etc/ripple/rdke/northamerica/ripple.config.json
IMAGE_CLASSES += "ripplemigrationoverrideconfig"
# Install:
#  /etc/authservice/config.json
IMAGE_CLASSES += "authservice-config"

# /etc/migration/boot_FSR.platform
IMAGE_CLASSES += "bootfsrconfig"