# Install:
#  /etc/entervices/privacyConfig.json
IMAGE_CLASSES += "entservicesprivacyconfig"

#  /etc/migration/entos_apps_migration.json
IMAGE_CLASSES += "appsmigrationconfig"

# /etc/sky/aisettings.overrides/migration-override.json
IMAGE_CLASSES += "aimigrationoverrideconfig"

# /etc/ripple/rdke/northamerica/ripple.config.json
IMAGE_CLASSES += "ripplemigrationoverrideconfig"
# /etc/authservice/config.json + /etc/rfcdefaults/authservice.ini
IMAGE_CLASSES += "authservice-config"

# /etc/migration/boot_FSR.platform
IMAGE_CLASSES += "bootfsrconfig"

# /etc/entservices/ttsConfig.json
IMAGE_CLASSES += "ttsconfig"

# /etc/mediarite/mediarite-product.cfg
IMAGE_CLASSES += "mediariteproductconfig"

# /etc/rfcdefaults/socprovisioning.ini
IMAGE_CLASSES += "socprovisioning-config"
